version: '3.9'

services:
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    image: nginx:1.27-alpine
    ports:
      - "${HOST_PORT_NGINX}:80"
    volumes:
      - ./../:/var/www/html:cached
      - ./logs/nginx:/var/log/nginx:delegated
      - ./config/nginx/develop/conf.d:/etc/nginx/conf.d:delegated
    restart: always

  js-dev:
    container_name: "${COMPOSE_PROJECT_NAME}-js-dev"
    build:
      context: ./config/php
      target: base
    command: 'npm run dev'
    ports:
      - "${HOST_PORT_JS_DEV}:5173"
    working_dir: /var/www/html
    volumes:
      - ./../:/var/www/html:cached
    restart: always

  php:
    volumes:
      - ./config/php/develop/ini:/usr/local/etc/php/custom.d:cached
