version: '3.9'

services:
    php:
        container_name: "${COMPOSE_PROJECT_NAME}-php"
        build:
            context: ./config/php
            target: base
        working_dir: /var/www/html
        volumes:
            - ./../:/var/www/html:cached
        restart: always

    mysql:
        container_name: "${COMPOSE_PROJECT_NAME}-mysql"
        image: mysql:9.0
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "${HOST_PORT_MYSQL}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always

volumes:
    mysql-data:
